kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: time-manager-db1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi